# https://aka.ms/yaml
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - .gitignore
    - .editorconfig
    - .github
    - README.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - SECURITY.md
    - LICENSE.txt
    - azure-pipelines.yml
    - docs
    - basis-set

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- script: python3 scripts/build.py --install-build-tools
  displayName: 'Install Build Tools'

- script: python3 scripts/build.py --build --release --debug
  displayName: 'Build LightAIMD'

- script: python3 scripts/build.py --sanity-test --release --debug
  displayName: 'Run Sanity Test'
